import { Sora,  } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
  display: 'swap',
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
